### ISSUE TITLE
wp-db.php failed to open stream - line 1708

### ISSUE THREAD

**Issue by dpsjallen** [ProjectNami/projectnami#119]
Hi,

On a clean copy of projectnami-master we are getting the following error on a local install.
![wp-db_php_error](https://cloud.githubusercontent.com/assets/3219511/17309741/78d3df46-57fd-11e6-84eb-b796d90987c2.png)

Warning: error_log(D:\home\LogFiles\php_errors.log): failed to open stream: Permission denied in E:\wp-sqlsrv\sitename\wp-includes\wp-db.php on line 1708 Warning: error_log(D:\home\LogFiles\php_errors.log): failed to open stream: Permission denied in E:\wp-sqlsrv\sitename\wp-includes\wp-db.php on line 1708

When I revert back to wp-db.php from a February release of wp-db.php this error doesn't occur.

Thanks,
Josh

**Comment by MOCLW** [comment]
Getting the same error with a new installation. The project theme is a woocommerce template that includes Cherry Framework.

Warning: error_log(D:\home\LogFiles\php_errors.log): failed to open stream: Permission denied in C:\WS\sitename\wp-includes\wp-db.php on line 1708

Thanks,
Louis

**Comment by patrickebates** [comment]
Just pushed a commit to Master that should clear this up.  Seems that a hard reference to the PHP error log location used by Azure Web Sites was included in a pull request and we failed to catch it.

Thanks for the notice.

**Comment by patrickebates** [comment]
Did this solve the issue for you two?  I'd like to close the ticket if this is corrected.  Thanks.

**Comment by dpsjallen** [comment]
Yes, thank you.

**Comment by MOCLW** [comment]
Yes! This resolved the issue. Thank you


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Patrick Bates <notifications@github.com> Date: 8/3/16  5:50 PM  (GMT-08:00) To: ProjectNami/projectnami <projectnami@noreply.github.com> Cc: MOCLW <lwalker@mocproducts.com>, Comment <comment@noreply.github.com> Subject: Re: [ProjectNami/projectnami] wp-db.php failed to open stream - line
  1708 (#119) 
Did this solve the issue for you two?  I'd like to close the ticket if this is corrected.  Thanks.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ProjectNami/projectnami","title":"ProjectNami/projectnami","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/modules/aws/aws-bg.jpg","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ProjectNami/projectnami"}},"updates":{"snippets":[{"icon":"PERSON","message":"@patrickebates in #119: Did this solve the issue for you two?  I'd like to close the ticket if this is corrected.  Thanks."}],"action":{"name":"View Issue","url":"https://github.com/ProjectNami/projectnami/issues/119#issuecomment-237419346"}}}
