### ISSUE TITLE
Installation error "on premise"

### ISSUE THREAD

**Issue by TheMFridge** [ProjectNami/projectnami#150]
Hi,

while trying to install Project Nami on my local dev-machine, (Win 10 Pro, IIS, PHP7, SQL 2016) i ran into the error "PHP Warning: sqlsrv_query() expects parameter 1 to be resource, null given in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1819". The error occurs directly after unpacking the files in my IIS Folder and open the Web with IE.

It seems to be a Problem with the SQL-Server Driver dll. PHP Info displays sqlsrv ExtensionVer:4.0.8629.3  
and pdo_sqlsrv ExtensionVer: 4.0.8629.3.

What am I doing wrong?

**Comment by patrickebates** [comment]
This happens before you get to any of the installation steps?  Is there an existing wp-config.php in your folder?

**Comment by calway** [comment]
I just posted in Issue #160 about my problems and noticed that the php56_errors.log has the exact same error. It also happens during the initial setup of Project nami. As stated in that issue I am running on Windows 2012R2 with a separate VM running SQL2016 Express and cannot get passed the setup-config.php page due to problems connecting to the sql database/server.

**Comment by Amith211** [comment]
Hi,
I'm also having the same issue on a fresh install of PN using two separate VMs; one with IIS and the other with SQL Server 2016 Dev Edn (SP1 CU5) both are running Server 2016 (Core).

- PHP 7.1
- sqlsrv & pdo_sqlsrv 4.1.6.1
-  PN 1.5.5

The error happens immediately before any installation steps stating:
"PHP Warning:  sqlsrv_query() expects parameter 1 to be resource, null given in [redacted]\wp-includes\wp-db.php on line 1829
PHP Warning:  sqlsrv_query() expects parameter 1 to be resource, null given in [redacted]\wp-includes\wp-db.php on line 1829"

The drives are pre-release versions so that may be the cause, either with a bug or a breaking change. (https://github.com/Microsoft/msphpsql/issues/137)

**Comment by patrickebates** [comment]
What about rolling back to PHP 7.0?  So far I've been unsuccessful at getting PN to run on 7.1 on Azure Web Apps, which I understand is related to the drivers.

**Comment by Amith211** [comment]
Thanks, using PHP 7.0 fixed the issue.
