### ISSUE TITLE
Azure Recomended Indexes

### ISSUE THREAD

**Issue by RehanSaeed** [ProjectNami/projectnami#173]
Azure recomends that I add the following indexes. Perhaps this should be built into Project Nami?

![capture](https://cloud.githubusercontent.com/assets/2270364/22084177/eee12140-ddc6-11e6-9737-1e2b8115cf4b.PNG)

**Comment by patrickebates** [comment]
We've considered adding some of the indexes Azure has recommended, but our experience is that different indexes are suggested depending on the usage patterns of each site.  Furthermore, some of the recommendations we've tested on various production sites were actually rolled back by Azure because they performed worse than the default.

For the moment, we suggest that you try the indexes for yourself and see how they perform.  Note that Azure will monitor the ones you create through this interface and will roll back any that it determines are harmful to performance.

Finally, if you happen to see one labeled High Impact please let us know.  So far we've not see any ourselves with PN, though we do with other applications.  An index that rises to that level may be worth including in PN.

**Comment by RehanSaeed** [comment]
So general advice is go with the Azure recommendation. Thanks!
