### ISSUE TITLE
Recommended security?

### ISSUE THREAD

**Issue by charlesroddie** [ProjectNami/projectnami#193]
Our site just got hacked so I am wondering:

If Nami users have any recommended security plugins. (Wordfence does not work I think.) In particular if there is a way to scan the deployment for suspicious files.

Any best practices that would secure a Project Nami site?

Thanks!

**Comment by patrickebates** [comment]
Wordfence certainly is not an option.  It will treat all modification for SQL Server as suspect files.

We'll have to give some thought to this.

Curious though how they got in.  Did they exploit a plugin or something in Core?
Any chance you use Revolution Slider?

**Comment by blachawk** [comment]
You could try Bullet Proof Security (BPS)

**Comment by charlesroddie** [comment]
We don't know how they got in a few months ago. Perhaps we didn't keep an eye on updates. Our main addon is the Divi theme.

We are using Bullet Proof Security now and it does seem compatible and does seem to be doing its job.

**Comment by joegasper** [comment]
Wordfence is [not supported](https://docs.wordfence.com/en/Wordfence_system_requirements#Operating_system) on IIS.  

Sucuri works well, minus the mentioned "problem" with "suspicious" files caused by the Nami changes.

Jetpack [also works](https://wponmssql.azurewebsites.net/blog/2017/05/02/site-update-may-2017/) and includes some brute force protection.
