### ISSUE TITLE
UTF8 character display issues

### ISSUE THREAD

**Issue by kfallstrom** [ProjectNami/projectnami#199]
My team and I have been working to migrate an existing WP install into a default NAMI install on Azure (followed the usual deploy to Azure recipe, then 1) added the plugins that were missing, 2) created missing tables).  I used UTF8 CSV files (one per table) and an SSIS ETL to load the data into the new SQL Server tables.  After the import, when posts are rendered, some characters display �  rather than the actual character value. It seems as though the install is limited in its character set support, though I feel certain that's not the case because of the results of direct queries to the database.

For example - --> (HTML safe &dash;) ,§ --> (HTML safe &sect;):

When I run a query against the database, I can see these characters returned correctly, but in the rendered HTML pages, it displays �.

Any ideas?

**Comment by patrickebates** [comment]
Yes.  We had some issues with UTF-8 support initially, so the default is to not force it on the driver when connecting to the database.  Those driver issues have since been resolved, but to guarantee compatibility with existing installs it is still not the default setting.  You can enable it through an App Setting

https://github.com/ProjectNami/projectnami/issues/17#issuecomment-244518219

App Setting of ProjectNami.UTF8 can now be set to 1 to force UTF-8 connections on the driver

Hopefully you haven't written any new data to the database, as setting this value will make your UTF-8 content work properly but cause similar corruption to what you are seeing now to any new data.

**Comment by kfallstrom** [comment]
Thanks Patrick!

I set the appSetting and everything is working great now.

Thanks for an awesome product!

**Comment by vageliskatsiotis** [comment]
Hi. You mean App Setting as in IIS Application Settings or in web.config file? Having trouble locating this.
Thank you.

**Comment by patrickebates** [comment]
Either or both.  Technically they are one and the same.

**Comment by vageliskatsiotis** [comment]
Thank you very much @patrickebates !
