### ISSUE TITLE
Keep on loading after being idle

### ISSUE THREAD

**Issue by arnoldpalar** [ProjectNami/projectnami#213]
Hi,

Found out it will keep on loading after being idle for a while and I need to restart the apache server to get it loaded normally. My Project Nami installation environment is MS Win Server 2012, PHP 7, Apache 2.4 server, MSSQL 2012 DB (installed on different machine but there is no problem with the network). Is there any configuration to tune it up?

Regards,
Arnold.

**Comment by patrickebates** [comment]
I'm not familiar with operating PN in Apache on Windows.  But I do know that with IIS you can have startup delays after the site has gone idle because it will be purged from memory.  One way to fix this is by using some sort of heartbeat ping to the web server.  On Azure, this is the AlwaysOn setting on the Web App.

Note that you can run PN on Linux now thanks to the availability of SQL Server drivers for the platform.  If you need to run in Apache or NGINX, you may want to look at that option as well.

**Comment by arnoldpalar** [comment]
Hi @patrickebates, yes I think implementing PN in Apache on Windows is not a common use. We will try the linux option and see how. Thanks!!
