### ISSUE TITLE
$worked = file_put_contents("/".$this->filepath

### ISSUE THREAD

**Issue by AndyNormore** [ProjectNami/projectnami#227]
Hi, great platform. 

I encountered this bug in the last standalone plugin from 2013. I had to update that file, and am surprised it's still here.

/wp-includes/fields_map.php

line 214

$worked = file_put_contents("/".$this->filepath

I had to add the / path, as it was trying to write from the relative path!

I am using PHP 7, fresh installed. Maybe it's a php5 -> 7 thing? 

Anyway, fixing this let me install. CHEERS.

**Comment by PHuhn** [comment]
Hi Andy:
I encountered the same issue.  The file /wp-includes/fields_map.php needs to dynamically create  /wp-includes/fields_map.parsed_types.php.  In order to do this the executing process needs to have modify rights to the wp-includes folder.  In generic implementations, that user is IUSR.   To find the user, 
click on web-site => Authentication => right-click Anonymous Authentication select ‘Edit…’.  FYI, you will also need to do the same thing for wp-content, in order to upload images.
Alternately, you can manually create the file and add one line of code:
`<?php return array ( '' => array ( ), ) ?>
`
I initially, did the latter solution, but have gone to the first solution (though it has security implications).  I am using my personal computer to try things out.
Phil

**Comment by geoffmunn** [comment]
I've also found this path problem, in fields_map.php. Adding the forward slash fixed it.

This was using PHP 7 and Centos 7.2.

**Comment by patrickebates** [comment]
I was already confused about this in general, as I've never encountered this issue after the thousands of deployments I've done myself.  But now to see that it's happening on multiple OS platforms...

I think it's time to revisit.  Off the cuff, one potential solution comes to mind, but it would probably be a breaking change for prior installs.  Need to test and consider more options.

**Comment by geoffmunn** [comment]
Maybe a check on $this->filepath to see if it has a prepending slash, and if it doesn't, add one?

**Comment by geoffmunn** [comment]
Ok, so I've had a quick look - is there a reason why you are using 'trim' instead of 'rtrim' on line 46 on fields_map.php?
```php
$this->filepath = trim(str_replace('mu-plugins/wp-db-abstraction/translations/sqlsrv', '', strtr(dirname(__FILE__), '\\', '/')), '/') . $loc . '/fields_map.parsed_types.php';
```

If you change it to 'rtrim' then the problem goes away, and shouldn't affect other OSs or installs.
