### ISSUE TITLE
MySQL to AzureSQL -> UTF-8 to Latin1

### ISSUE THREAD

**Issue by simmyg89** [ProjectNami/projectnami#24]
Hi all,

I moved all my Wordpress sites to Azure using the SQL Server Migration Assistant and I've discovered this charset issue due to this porting, because all the special characters went wrong.

I've resolved this issue setting the implicit SQL Server UTF-8 conversion in the connection string:
"CharacterSet" => "UTF-8"

Reference:
https://msdn.microsoft.com/en-us/library/cc626307(v=sql.105).aspx

Hope this can be added in the wp-db.php (line 1402 and 1404) file and also can help anyone else.

Best regards

**Comment by patrickebates** [comment]
That's interesting.  We've experienced mixed results with setting UTF-8 on the connection string in the past.

The difference must be with your use of the Migration Assistant rather than using the Export and Import routines within WordPress/ProjectNami.  I will need to test the impact of setting UTF-8 with an imported site before making this change.

**Comment by yorek** [comment]
I had collations problem too, but I moved the content manually from On-Premise SQL Server to Azure. The main problem is that Wordpress expect UTF-16 characters encoded in UTF-8 format. Here's an example of how such conversion can be done: http://stackoverflow.com/questions/6198744/convert-string-utf-16-to-utf-8-in-c-sharp. Here you can try utf-8 encoding online: http://www.cafewebmaster.com/online_tools/utf8_encode

**Comment by leonardopires** [comment]
I had this problem too and the @simmyg89 fix solved the issue.

However, the charset issue happened in a table created AFTER the migration, and with data inserted using a regular SQL Script.

The irony is that it wasn't any complex asian character that made me notice that. It was a mere spanish ñ.

**Comment by patrickebates** [comment]
Can you confirm if you migrated to Azure from SQL Server or MySQL?  And I assume that you used a third-party tool rather than using the built-in Import and Export functions of WordPress and Project Nami?

**Comment by leonardopires** [comment]
@patrickebates I've first migrated from MySQL using the Migration Assistant.
Then I've created a custom database table for a plugin (in both SQL Azure and my local SQL Express) and inserted via a SQL Script (from management studio) some items in the database. Two of them were "El Niño" and "La Niña".

They were both appearing as "El Ni?o" and "La Ni?a". I've set the charset header to UTF-8 and nothing.

I've then ran mb_detect_encoding on the column and got "UTF-8" as expected, but the result was appearing with the question mark instead of the proper character.

When I've changed the connection string as @simmyg89 has suggested, everything worked. And now I can see my "ñ" properly. 

The interesting note is that now the JSON that the plugin returns contains the escaped character rather than "ñ" itself.

**Comment by jonjander** [comment]
I have the same issue when using migration assistant for mysql. @simmyg89 's solution solves the problem but I dont want to modify the code. Why does project nami save åäö like Ã¥Ã¤Ã¶ in the db?

**Comment by patrickebates** [comment]
When PN was first created, we encountered issues with the then-current SQL driver and the UTF-8 setting.  The workaround was to just not use it, as WordPress would properly handle the strings as they came back out of the database.

This was seen again with the early previews of the SQL driver for PHP 7, and it took a few builds before the UTF-8 option was fully supported.

Based on testing that we've done, switching now to using UTF-8 for all deployments will result in breaking the vast majority of sites.  So for the last few weeks, I've been debating an App Setting / Env Var to turn UTF-8 on.  This way no code changes would be required for you and the few others in this situation.

I am curious though.  What prompted you to use the Migration Assistant?

**Comment by patrickebates** [comment]
Here's the commit from moments ago with the change.  Currently in the Master branch only, it would be included in the upcoming merge with WP 4.6

e109b07b401d44fa735848347c06a7f447a589ec

**Comment by patrickebates** [comment]
@jonjander Did this update help to resolve the issue?  In case you didn't see it in the commit, you now have the option to use an App Setting of ProjectNami.UTF8 which can be defined in either web.config or App Settings of either IIS or the Azure portal.  Setting it to 1 will enable UTF-8 mode in the SQL connection.

You may download from the Master branch to test this update.

**Comment by patrickebates** [comment]
Closing this ticket as there's been no further comment.  UTF-8 can now be forced via an App Setting, and this may be added as a default for Deploy To Azure after the drivers for PHP 7 are ready there.
